### ISSUE TITLE
How can we add new stations data?

### ISSUE THREAD

**Issue by amirmojiry** [yasandev/tehro-database#1]
Hi dear @yasandev,
I would like to ask that how can we add new stations data?
Thanks

**Comment by yasanglass** [comment]
Hi,
I will update the readme file with more information today/tomorrow.

I can help you directly here until I update the readme but I'm not sure what your exact issue is!?

Do you have problems understanding the database structure or simply how you can modify.db files?! Or something else?!

**Comment by amirmojiry** [comment]
Thank you. I'm just curious about the contribution method. If I want to add new information, do I have to add it to SQL and JSON files directly?

**Comment by yasanglass** [comment]
All changes in every commit must be reflected in all 3 database variants (db, json & SQL).

I personally modify the db file using [DB Browser for SQLite](https://sqlitebrowser.org/). I also use the same software to export json and SQL files of the database.

This is due to the issue that .db files do not have visible diffs in git. I guess it can be fixed by just using the SQL file but I don't know if that would be the best possible approach yet since that's not perfect as well.

If you have suggestions on how this should be done please let me know.

**Comment by yasanglass** [comment]
@amirmojiry I removed the JSON exports to make the process easier. I think I probably should also add a picture of the schema to make it easier for new people to understand it so they can update the data easier!?
